repos:
  - repo: local
    hooks:
      - id: black
        name: Run black (local venv)
        entry: python run_black.py
        language: system
        types: [python]
        pass_filenames: true
        args: ["--line-length=88"]
